// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjRwn7VBLXaXgLFrJQ8KvC3xGZ9yKwP8Q',
    appId: '1:123456789:web:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'attendance-qr-upc',
    authDomain: 'attendance-qr-upc.firebaseapp.com',
    storageBucket: 'attendance-qr-upc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAheO0IAzph7OMwHz5AR9YAy7rKuA36XKE',
    appId: '1:28589149936:android:970f57b74bba35c420bc35',
    messagingSenderId: '28589149936',
    projectId: 'attendance-qr-upc',
    storageBucket: 'attendance-qr-upc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjRwn7VBLXaXgLFrJQ8KvC3xGZ9yKwP8Q',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'attendance-qr-upc',
    storageBucket: 'attendance-qr-upc.appspot.com',
    iosBundleId: 'com.upc.attendanceQrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjRwn7VBLXaXgLFrJQ8KvC3xGZ9yKwP8Q',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'attendance-qr-upc',
    storageBucket: 'attendance-qr-upc.appspot.com',
    iosBundleId: 'com.upc.attendanceQrApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjRwn7VBLXaXgLFrJQ8KvC3xGZ9yKwP8Q',
    appId: '1:123456789:web:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'attendance-qr-upc',
    authDomain: 'attendance-qr-upc.firebaseapp.com',
    storageBucket: 'attendance-qr-upc.appspot.com',
  );
}
